plugins {
	id 'java'
	id 'org.springframework.boot'
	id 'io.spring.dependency-management' version '1.1.2'
}

allprojects {
	group = 'com.jsonwebtoken'
	version = '1.2.1'
	java {
		sourceCompatibility = '1.8'
	}
}

subprojects {
	apply plugin: 'java'
	apply plugin: 'org.springframework.boot'
	apply plugin: 'io.spring.dependency-management'

	repositories {
		mavenCentral()
	}

	dependencies {
		// 필수적
		implementation 'org.springframework.boot:spring-boot-starter-web'
		implementation group: 'org.json', name: 'json', version: '20230227'
		implementation 'org.apache.commons:commons-lang3:3.12.0'
		implementation 'org.bitcoinj:bitcoinj-core:0.15.10'
		implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-csv'
		implementation 'com.github.wnameless.json:json-flattener:0.16.0'
		implementation 'com.google.code.gson:gson'
		implementation 'com.google.guava:guava:31.1-jre'
		implementation 'org.projectlombok:lombok'
		implementation 'org.slf4j:slf4j-api:1.7.32'

		// 선택적 / 문서용 (compileOnly)
		compileOnly 'org.springframework.boot:spring-boot-devtools'

		// 컴파일타임 시
		compileOnly 'org.projectlombok:lombok'
		annotationProcessor 'org.projectlombok:lombok'
		annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

		// 테스트용
		testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.2'
		testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.2'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}
	test {
		useJUnitPlatform()
	}
}