### 서버 관리
server:
  ### 내장 WAS 관리
  port: 28080

##### 문서 관리
springdoc:
  swagger-ui:
    tagsSorter: alpha
    operationsSorter: alpha
    docExpansion: none
    path: /api

### JWT4J 토큰 관리
token:
  info:
    name: JWT4J
    path: ./files/licAgentKey/        # 키 페어 저장 경로
#    path: ./files/        # 키 페어 저장 경로
    key-size: 2048        # 키 페어 크기
    typ: jsonwebtoken     # 토큰 타입
    exp: 3600000          # 토큰 만료 시간 (밀리초 단위, 1시간)
    alg: RSA              # 토큰 암호화 알고리즘
    iss: jwt4j-core       # 토큰 발급자
    sub: jwt4j-lite       # 토큰 주제
