plugins {
	id 'java'
}

ext {
	libName = 'jsonwebtoken-app'
	libVersion = version
}

jar {
	enabled = true
	archiveBaseName.set(libName)
	archiveVersion.set(libVersion)
}

bootJar {
	enabled = false
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'io.springfox:springfox-swagger-ui:3.0.0'
	implementation 'io.springfox:springfox-boot-starter:3.0.0'

	implementation project(':jsonwebtoken-core')
}