plugins {
	id 'java'
}

ext {
	libName = 'jsonwebtoken'
	libVersion = version
}

jar {
	enabled = true
	archiveBaseName.set(libName)
	archiveVersion.set(libVersion)
}

bootJar {
	enabled = false
}

tasks.named('test') {
	useJUnitPlatform()
}

task sourcesJar(type: Jar) {
	from sourceSets.main.allSource
	archiveBaseName.set(libName)
	archiveVersion.set(libVersion)
	archiveClassifier.set('sources')
}

task javadocJar(type: Jar, dependsOn: javadoc) {
	archiveBaseName.set(libName)
	archiveVersion.set(libVersion)
	archiveClassifier.set('javadoc')
}

javadoc {
	options.encoding = 'UTF-8'
	options.addStringOption('Xdoclint:none', '-quiet')
}

artifacts {
	archives sourcesJar
	archives javadocJar
}
configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
}

